version: "3.8"
services: 
  mysql:
    image: mysql:8.0.26
    ports: 
      - 3306:3306
    volumes: 
      - ./assets/sql/database_ddl.sql:/docker-entrypoint-initdb.d/openmarket.sql
    environment: 
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=openmarket
      - MYSQL_USER=openmarketuser
      - MYSQL_PASSWORD=openmarketpassword
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment: 
      - PMA_HOSTS=mysql
      - PMA_USER=openmarketuser
      - PMA_PASSWORD=openmarketpassword