openapi: 3.0.0
info:
  title: Open Market
  description: Another API to manager Open Markets.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local Environment
paths:
  /markets:
    post:
      summary: Create a New Market
      description:
      consumes:
        - application/json      
      parameters:
        - in: body
          name: market
          description: Market to be created
          schema:
            type: object
            required:
              - name
              - neighbor
              - district
              - region
            properties:
              name:
                type: string
              neighbor:
                type: string
              district:
                type: string
              region:
                type: string
      responses:
        '201':
          description: Market Created
    get:
      summary: Get markets by filter
      description:
      consumes:
        - application/json      
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /markets/{id}:
    delete:
      summary: Delete a Market
      description:
      consumes:
        - application/json      
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: id of the market to be deleted
      responses:
        '200':
          description: Market Deleted
    put:
      summary: Update a market
      description:
      consumes:
        - application/json      
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: id of the market to be updated
        - in: body
          name: market
          description: Market to be created
          schema:
            type: object
            properties:
              name:
                type: string
              neighbor:
                type: string
              district:
                type: string
              region:
                type: string
      responses:
        '200':
          description: Market Updated
