openapi: 3.0.0
info:
  title: Open Market
  description: Another API to manager Open Markets.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local Environment
paths:
  /markets:
    post:
      summary: Create a New Market
      description:
      consumes:
        - application/json
      parameters:
        - in: body
          name: market
          description: Market to be created
          schema:
            type: object
            required:
              - name
              - neighborhood
              - district
              - region
            properties:
              name:
                type: string
              neighborhood:
                type: string
              district:
                type: string
              region:
                type: string
      responses:
        '201':
          description: Market Created
          content:
            application/json:
              schema:
                type: object
                propeties:
                  status:
                    type: number
                  body:
                    type: string
    get:
      summary: Get markets by filter
      description:
      consumes:
        - application/json
      parameters:
        - in: query
          name: market
          description: Market to be created
          schema:
            type: object
            properties:
              name:
                type: string
              neighborhood:
                type: string
              district:
                type: string
              region:
                type: string
      responses:
        '200':
          description: List of Market Results
          content:
            application/json:
              schema:
                type: object
                propeties:
                  status:
                    type: number
                    example: 200
                  body:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: 'Market x'
                        neighborhood:
                          type: string
                          example: 'Centro'
                        district:
                          type: string
                          example: 'Niteroi'
                        region:
                          type: string
                          example: 'Rio de Janeiro'
  /markets/{id}:
    delete:
      summary: Delete a Market
      description:
      consumes:
        - application/json
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: id of the market to be deleted
      responses:
        '200':
          description: Market Deleted
          content:
            application/json:
              schema:
                type: object
                propeties:
                  status:
                    type: number
                  body:
                    type: string
    put:
      summary: Update a market
      description:
      consumes:
        - application/json
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: id of the market to be updated
        - in: body
          name: market
          description: Market to be created
          schema:
            type: object
            properties:
              name:
                type: string
              neighborhood:
                type: string
              district:
                type: string
              region:
                type: string
      responses:
        '200':
          description: Market Updated
          content:
            application/json:
              schema:
                type: object
                propeties:
                  status:
                    type: number
                  body:
                    type: string
